<a href="https://colab.research.google.com/github/Riturajsinha04/Python/blob/main/Class_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
matrix = np.random.randint(1, 90, (5, 5))
print("Matrix: ", matrix)

row_mean = np.mean(matrix, axis=1, dtype=int)
print("Row_mean", row_mean)

col_mean = np.mean(matrix, axis=0, dtype=int)
print("Col_mean: ", col_mean)

print("Sorted_row: ", np.sort(matrix, axis=1))
print("Sorted_col: ", np.sort(matrix, axis=0))

row_sum = np.sum(matrix, axis=1)
col_sum = np.sum(matrix, axis=0)
print("Sum of Row: ", row_sum)
print("Sum of Col: ", col_sum)

matrix = np.where(matrix % 2 == 0, -1, matrix)
print(matrix)

neg_count = np.sum(matrix < 0, axis=0)
print(neg_count)

Matrix:  [[89 17  8 52 10]
 [74 29 84 42 78]
 [56 35 54 22 10]
 [83 33 57 40 57]
 [50 16 81 34 87]]
Row_mean [35 61 35 54 53]
Col_mean:  [70 26 56 38 48]
Sorted_row:  [[ 8 10 17 52 89]
 [29 42 74 78 84]
 [10 22 35 54 56]
 [33 40 57 57 83]
 [16 34 50 81 87]]
Sorted_col:  [[50 16  8 22 10]
 [56 17 54 34 10]
 [74 29 57 40 57]
 [83 33 81 42 78]
 [89 35 84 52 87]]
Sum of Row:  [176 307 177 270 268]
Sum of Col:  [352 130 284 190 242]
[[89 17 -1 -1 -1]
 [-1 29 -1 -1 -1]
 [-1 35 -1 -1 -1]
 [83 33 57 -1 57]
 [-1 -1 81 -1 87]]
[3 1 3 5 3]


In [2]:
mat_stock = np.random.randint(20, 80, (5, 5))
print("Stock: ", mat_stock)

mat_demand = np.random.randint(20, 80, (5, 5))
print("Demand: ", mat_demand)

remaining = mat_stock - mat_demand
print(remaining)

total_shortage = np.sum(np.where(remaining < 0, -remaining, 0))
print(total_shortage)

neg_values = np.where(remaining < 0, 0, remaining)
print(neg_values)

zero_stock = np.sum(np.where(remaining > 1, 1, remaining))
print(zero_stock)

print("Sorted_row: ", np.sort(remaining, axis=1))

Stock:  [[70 75 34 48 79]
 [44 24 53 30 28]
 [29 39 30 70 68]
 [76 61 55 34 43]
 [56 51 52 27 78]]
Demand:  [[38 51 72 44 38]
 [78 29 21 25 22]
 [66 71 70 46 68]
 [50 72 57 55 38]
 [39 77 70 76 72]]
[[ 32  24 -38   4  41]
 [-34  -5  32   5   6]
 [-37 -32 -40  24   0]
 [ 26 -11  -2 -21   5]
 [ 17 -26 -18 -49   6]]
313
[[32 24  0  4 41]
 [ 0  0 32  5  6]
 [ 0  0  0 24  0]
 [26  0  0  0  5]
 [17  0  0  0  6]]
-301
Sorted_row:  [[-38   4  24  32  41]
 [-34  -5   5   6  32]
 [-40 -37 -32   0  24]
 [-21 -11  -2   5  26]
 [-49 -26 -18   6  17]]


In [3]:
import pandas as pd

In [4]:
file_ = pd.read_csv('student_data.csv')

# print(file_.head(8))

print(file_.tail(8))

# print(file_)


      study_hours  attendance  sleep_hours  internet_usage  \
9992            5         100            9               2   
9993           10          86            9               9   
9994            4          53            7               8   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
9992                      9              62      100.00           Placed  
9993                     15              63      100.00           Placed  
9994                     10              71       85.02           Placed  
9995                      8              88       69.31       Not Placed  
9996                      4              87      100.00           