<a href="https://colab.research.google.com/github/Riturajsinha04/Python/blob/main/Numpy-DAU-03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY
import numpy as np


In [ ]:
a = np.array([1,3,9,0,'2'])
print(a)

['1' '3' '9' '0' '2']


In [ ]:
np_arr = np.array([3,3,3,3, 3.3, 'hello', False])
print(bool(np_arr[-1]))
#first the values are converted to strings and then when we print it the bbool having vakue as string always print true.

a = False
print(bool(a))

True
False


In [ ]:
a = np.zeros((2,3,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#ones
a = np.ones(3)
print(a)

[1. 1. 1.]


In [ ]:
#empty
a = np.empty(3,dtype=int)
print(a)

[4607182418800017408 4607182418800017408 4607182418800017408]


In [ ]:
#full <--- create array with any value
a = np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [ ]:
#linespace


In [ ]:
a = np.random.choice([2,4,2,9],2)
print(a)

[4 2]


In [ ]:

a = np.array([1,2,3,4])
b = np.array([9,6,8,7])
print(a*2)
print(a+b)
print(a/b)
print(a*b)
print(a-b)

[2 4 6 8]
[10  8 11 11]
[0.11111111 0.33333333 0.375      0.57142857]
[ 9 12 24 28]
[-8 -4 -5 -3]


In [ ]:
#transpose
a = np.array([[1,2,3],
             [4,5,6]])
print(a)
b = a.transpose()
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
scores = []

days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

for day in days:
    score = int(input(f"Enter the score for {day}: "))
    scores.append(score)
    score = np.array(scores)

    print("Scores", scores)
    print("Maximum Score", np.max(score))
    print("Minimum Score", np.min(score))
    print("Average Score", np.mean(score))
    print("Standard deviation", np.std(score))

Scores [45]
Maximum Score 45
Minimum Score 45
Average Score 45.0
Standard deviation 0.0
