<a href="https://colab.research.google.com/github/Riturajsinha04/Python/blob/main/Numpy-Class-03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#NUMPY
import numpy as np


In [ ]:
a = np.array([1,3,9,0,'2'])
print(a)

['1' '3' '9' '0' '2']


In [ ]:
np_arr = np.array([3,3,3,3, 3.3, 'hello', False])
print(bool(np_arr[-1]))
#first the values are converted to strings and then when we print it the bbool having vakue as string always print true.

a = False
print(bool(a))

True
False


In [ ]:
a = np.zeros((2,3,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#ones
a = np.ones(3)
print(a)

[1. 1. 1.]


In [ ]:
#empty
a = np.empty(3,dtype=int)
print(a)

[4607182418800017408 4607182418800017408 4607182418800017408]


In [ ]:
#full <--- create array with any value
a = np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [3]:
a = np.arange(2, 8, 2, dtype=int)
print(a)


[2 4 6]


In [4]:
#linespace
a = np.linspace(0, 10, 3, dtype=int)
print(a)


[ 0  5 10]


In [8]:
a = np.array([[10, 20, 30], [40, 50, 60]])
print(a.shape)


(2, 3)


In [9]:
a = np.array([[10, 20, 30], [40, 50, 60]])
print(a.size)

6


In [10]:
a = np.random.randint(2, 8, size=5, dtype=int)
print(a)

[5 5 2 3 4]


In [7]:
#random choice
a = np.random.choice(['Apple', 'Banana', 'Orange'])
print(a)

Banana


In [11]:
#BROADCASTING
a = np.array([4, 6, 12, 14])
b = np.array([2, 3, 6, 7])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 6  9 18 21]
[2 3 6 7]
[ 8 18 72 98]
[2. 2. 2. 2.]


In [12]:
a = np.random.randint(5, 15, 6)
print(a)
b = a.reshape([2, 3])
print(b)

[ 8 12 10  6 14  6]
[[ 8 12 10]
 [ 6 14  6]]


In [13]:
a = np.random.randint(5, 15, 6)

b = a.reshape(2, 3)
print(b)
print(b.T)

[[11  6  6]
 [ 7  7  9]]
[[11  7]
 [ 6  7]
 [ 6  9]]


In [14]:
a = np.random.randint(5, 15, 6)
b = np.random.randint(5, 15, 6)
c = np.concatenate((a, b))
print(a)
print(b)
print(c)


[14 14  6 12 11  7]
[ 6  5 12 13  6  9]
[14 14  6 12 11  7  6  5 12 13  6  9]


In [15]:
a = np.random.randint(5, 15, 6)
b = np.random.randint(5, 15, 6)
c = np.concatenate((a, b), axis=0)
print(a)
print(b)
print(c)

[13 11 12  5  7  8]
[10 10 10  6 14 14]
[13 11 12  5  7  8 10 10 10  6 14 14]


In [16]:
a = np.random.randint(5, 15, 6).reshape(2, 3)
b = np.random.randint(5, 15, 6).reshape(2, 3)
c = np.concatenate((a, b), axis=1)
print(a)
print(b)
print(c)

[[11  7 14]
 [11 11  7]]
[[ 9  8  7]
 [ 5 12 12]]
[[11  7 14  9  8  7]
 [11 11  7  5 12 12]]


In [17]:
a = np.random.randint(2, 15, 6)
b = np.random.randint(1, 19, 6)
c = np.where(b > 2, b, a)
print(a)
print(b)
print(c)


[11  2  5  2  9 11]
[ 8 10  9  4 10 15]
[ 8 10  9  4 10 15]


In [18]:
a = np.random.randint(2, 15, 6)
print(a)
c = np.sort(a)
print(c)


[ 4  6  9  3  7 11]
[ 3  4  6  7  9 11]


In [19]:
a = np.random.randint(2, 15, 6)
b = np.random.randint(1, 19, 6)
print(a, b)
c = np.sum(a + b)
print(c)

[ 6 10  3 12 13  5] [10 10 12  5  5 13]
104


In [20]:
a = np.random.randint(2, 15, 6)
print(a)
c = np.mean(a)
print(c)


[13  2 13  3 10 14]
9.166666666666666


In [21]:
a = np.random.randint(2, 15, 6)
print(a)
c = np.std(a)
print(c)

[ 4 12  7 13  2 11]
4.13991411612474


In [22]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.min(a))


[13  7  8 12 11 10]
7


In [23]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.max(a))

[ 2 11  3  5  6 10]
11


In [24]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.unique(a))

[ 2  9  9  8 14  4]
[ 2  4  8  9 14]


In [25]:
a = np.random.randint(2, 15, 6)
b = np.random.randint(1, 19, 6)
print(a, b)
print(np.matmul(a, b))

[ 7  3 11 11 13  6] [ 5 16  5 18 14 12]
590


In [ ]:
#transpose
a = np.array([[1,2,3],
             [4,5,6]])
print(a)
b = a.transpose()
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [26]:
# Homework

# Copy concept

# A shop with different grocery items. Take 5 6 products alng with their prices, and perform operations.

scores = []
days = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun']
for i in range(7):
  # x = input(f'Scores on days{i}');
  scores = [int(x) for x in scores]
  print(scores)


[]
[]
[]
[]
[]
[]
[]


In [ ]:
scores = []

days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

for day in days:
    score = int(input(f"Enter the score for {day}: "))
    scores.append(score)
    score = np.array(scores)

    print("Scores", scores)
    print("Maximum Score", np.max(score))
    print("Minimum Score", np.min(score))
    print("Average Score", np.mean(score))
    print("Standard deviation", np.std(score))

Scores [45]
Maximum Score 45
Minimum Score 45
Average Score 45.0
Standard deviation 0.0
